package com.aihospital.triage.domain;

import com.aihospital.shared.model.Models.Evidence;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;
import java.util.List;

/** Turn-local references. A valid reference is not proof of semantic entailment. */
public final class AnswerEvidence {
    private AnswerEvidence() {}
    public record Reference(String id, String title, String source, String excerpt,
                            String contentHash, String applicability) {}
    public record Paragraph(String text, String kind, List<String> referenceIds) {}
    public record Draft(List<Paragraph> paragraphs, List<String> questions, List<String> uncovered) {}
    /** Separate model review, not clinical approval or booking authorization. */
    public record SupportReview(String status, List<String> issueCodes, Long elapsedMs,
                                Failure failure, Boolean thinkingEnabled, Integer inputTokens, Integer outputTokens) {
        public SupportReview { issueCodes = issueCodes == null ? List.of() : List.copyOf(issueCodes); }
    }
    /** Backend-owned query snapshot, never generated by the narration model. */
    public record ServiceNotice(List<String> messages, Boolean bookingAllowed) {
        public ServiceNotice { messages = messages == null ? List.of() : List.copyOf(messages); }
    }
    /** Allowlisted operational metadata only: never exception messages or response bodies. */
    public record Failure(String code, String causeType, Integer httpStatus,
                          List<String> causeChain, List<String> locations) {
        public Failure(String code, String causeType, Integer httpStatus) {
            this(code, causeType, httpStatus, List.of(), List.of());
        }
        public Failure {
            causeChain = causeChain == null ? List.of() : List.copyOf(causeChain);
            locations = locations == null ? List.of() : List.copyOf(locations);
        }
    }
    public record Generation(String phase, String finishReason, Integer inputTokens,
                             Integer outputTokens, Integer outputCharacters,
                             Boolean thinkingEnabled, String transport, Boolean jsonObjectEnabled, Integer thinkingBudget) {
        public Generation(String phase, String finishReason, Integer inputTokens,
                Integer outputTokens, Integer outputCharacters, Boolean thinkingEnabled, String transport, Boolean jsonObjectEnabled) {
            this(phase, finishReason, inputTokens, outputTokens, outputCharacters, thinkingEnabled, transport, jsonObjectEnabled, null);
        }
        public Generation(String phase, String finishReason, Integer inputTokens,
                Integer outputTokens, Integer outputCharacters, Boolean thinkingEnabled, String transport) {
            this(phase, finishReason, inputTokens, outputTokens, outputCharacters, thinkingEnabled, transport, null);
        }
        public Generation(String phase, String finishReason, Integer inputTokens,
                Integer outputTokens, Integer outputCharacters) {
            this(phase, finishReason, inputTokens, outputTokens, outputCharacters, null, null, null);
        }
    }
    public record Diagnostics(String traceId, String retrievalStatus, String validationStatus,
                              List<Reference> retrievedReferences, List<String> adoptedReferenceIds,
                              List<String> uncovered, String semanticSupport, Failure failure, Long elapsedMs,
                              Generation generation, SupportReview supportReview, ServiceNotice serviceNotice) {
        public Diagnostics(String traceId, String retrievalStatus, String validationStatus,
                List<Reference> retrievedReferences, List<String> adoptedReferenceIds,
                List<String> uncovered, String semanticSupport, Failure failure, Long elapsedMs,
                Generation generation) {
            this(traceId, retrievalStatus, validationStatus, retrievedReferences, adoptedReferenceIds,
                    uncovered, semanticSupport, failure, elapsedMs, generation, null, null);
        }
        public Diagnostics(String traceId, String retrievalStatus, String validationStatus,
                List<Reference> retrievedReferences, List<String> adoptedReferenceIds,
                List<String> uncovered, String semanticSupport, Failure failure, Long elapsedMs) {
            this(traceId, retrievalStatus, validationStatus, retrievedReferences, adoptedReferenceIds,
                    uncovered, semanticSupport, failure, elapsedMs, null);
        }
        public Diagnostics(String traceId, String retrievalStatus, String validationStatus,
                List<Reference> retrievedReferences, List<String> adoptedReferenceIds,
                List<String> uncovered, String semanticSupport) {
            this(traceId, retrievalStatus, validationStatus, retrievedReferences, adoptedReferenceIds,
                    uncovered, semanticSupport, null, null);
        }
        public Diagnostics {
            retrievedReferences = retrievedReferences == null ? List.of() : List.copyOf(retrievedReferences);
            adoptedReferenceIds = adoptedReferenceIds == null ? List.of() : List.copyOf(adoptedReferenceIds);
            uncovered = uncovered == null ? List.of() : List.copyOf(uncovered);
        }
    }
    public static List<Reference> references(List<Evidence> evidence) {
        var result = new java.util.ArrayList<Reference>();
        for (Evidence item : evidence) {
            result.add(new Reference("E" + (result.size() + 1), item.title(), item.source(), item.excerpt(),
                    hash(item.excerpt()), "UNKNOWN"));
        }
        return List.copyOf(result);
    }
    private static String hash(String text) {
        try { return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256")
                .digest(text.getBytes(StandardCharsets.UTF_8))); }
        catch (java.security.NoSuchAlgorithmException ex) { throw new IllegalStateException(ex); }
    }
}
