<script setup lang="ts">
import { ref } from 'vue'
import { api } from '../../api'
import type { HumanReview } from '../triage/types'
defineProps<{ page: string; knowledge: any[]; tools: any[]; calls: any[]; reviews: HumanReview[]; runtime: any; knowledgeRuntime:any; adminRoute: (page: string) => string; patientRoute: (page: string) => string }>()
defineEmits<{ addKnowledge: []; approveKnowledge:[id:string]; toggleTool: [tool: any]; runTool:[tool:any]; handleReview:[id:string,status:'ACCEPTED'|'CLOSED'] }>()
const query=ref(''), searchResults=ref<any[]>([]), searched=ref(false), searchError=ref(''), searching=ref(false)
async function searchKnowledge(){
  if(!query.value.trim())return
  searching.value=true;searchError.value=''
  try{searchResults.value=await api<any[]>(`/admin/knowledge/search?q=${encodeURIComponent(query.value.trim())}`);searched.value=true}
  catch(e:any){searchError.value=e?.message||'检索失败';searchResults.value=[];searched.value=true}
  finally{searching.value=false}
}
</script>

<template>
  <section class="admin-shell"><aside class="admin-side"><b>⌁ AI 智慧医院管理平台</b><a :class="{on:page==='dashboard'}" :href="adminRoute('dashboard')">⌂ 系统首页</a><p>AI 能力配置</p><a :class="{on:page==='knowledge'}" :href="adminRoute('knowledge')">▤ 医学知识库（RAG）</a><a :class="{on:page==='tools'}" :href="adminRoute('tools')">⚙ Agent 工具中心</a><a :class="{on:page==='observe'}" :href="adminRoute('observe')">◉ AI 调用观测</a><a :class="{on:page==='reviews'}" :href="adminRoute('reviews')">☏ 人工导诊申请</a><a :href="patientRoute('home')">← 返回患者端</a></aside><div class="admin-content">
    <div v-if="page==='dashboard'"><div class="admin-hero"><span>AI 智慧医院 · 智能导诊就诊平台</span><h1>您好，系统管理员 <label>管理员</label></h1><p>本机演示版：多轮预问诊、风险规则、知识检索、模拟挂号及人工复核申请。</p><b>预问诊　 危险信号拦截　 知识依据　 工具调用记录</b></div><h2>功能导航</h2><div class="admin-cards"><article><i>☷</i><h3>预问诊与智能导诊</h3><p>保存多轮症状与分诊版本，危险信号在生成挂号建议前拦截。</p></article><article><i>▤</i><h3>医学知识检索</h3><p>分段和相关度阈值；配置 Embedding 与 Qdrant 后可启用语义检索。</p></article><article><i>⚙</i><h3>工具中心</h3><p>本地医院演示数据通过统一工具边界执行，提供 MCP 协议入口。</p></article><article><i>◉</i><h3>调用与人工复核</h3><p>实际耗时和工具结果持久化；人工申请进入管理队列。</p></article></div></div>
    <div v-else-if="page==='knowledge'"><div class="admin-title"><div><h2>医学知识库 RAG</h2><p>当前模式：{{ knowledgeRuntime?.mode==='HYBRID_QDRANT'?'Qdrant 语义向量＋本地检索':'本地医学词＋字符向量检索' }}。低相关度自动拒答；新上传资料待审核。</p></div><button class="primary" @click="$emit('addKnowledge')">＋ 新增知识资料</button></div><form class="searchbar" @submit.prevent="searchKnowledge"><input v-model="query" placeholder="输入症状或问题，例如：咳嗽胸闷挂什么科"><button class="primary" type="submit" :disabled="searching">{{ searching?'检索中…':'检索' }}</button></form><div v-if="searched" class="knowledge-results"><h3>检索命中片段（{{ searchResults.length }}）</h3><p v-if="searchError" role="alert">{{ searchError }}</p><p v-else-if="!searchResults.length">未找到可信的相关知识片段，请更换检索词。</p><article v-for="(hit,index) in searchResults" :key="index" class="table-card"><b>{{ hit.title }}</b><p>{{ hit.excerpt }}</p><a v-if="hit.source?.startsWith('https://')" :href="hit.source.split(' | ')[0]" target="_blank" rel="noopener noreferrer">查看来源</a></article></div><div class="table-card"><table><thead><tr><th>资料标题</th><th>知识片段</th><th>状态</th><th>更新时间</th><th>索引方式</th></tr></thead><tbody><tr v-for="d in knowledge" :key="d.id"><td><b>{{ d.title }}</b></td><td>{{ d.chunks }} 个切片</td><td><label class="ready">{{ d.status }}</label></td><td>{{ new Date(d.updatedAt).toLocaleString() }}</td><td class="blue">{{ d.status==='READY'?knowledgeRuntime?.mode:'待审核' }}</td></tr></tbody></table></div></div>
    <div v-else-if="page==='tools'"><div class="admin-title"><div><h2>Agent 工具中心</h2><p>Agent 与 MCP 协议端点共用本地医院能力适配器；真实医院接口尚未接入。</p></div></div><div class="tool-pool"><b>当前启用的工具：</b><span v-for="t in tools.filter(t=>t.enabled)" :key="t.code">{{ t.code }}</span></div><div class="table-card"><table><thead><tr><th>工具编码</th><th>工具名称</th><th>工具说明</th><th>启用状态</th><th>执行</th></tr></thead><tbody><tr v-for="t in tools" :key="t.code"><td class="blue">{{ t.code }}</td><td><b>{{ t.name }}</b></td><td>{{ t.description }}</td><td><button class="switch" :class="{on:t.enabled}" @click="$emit('toggleTool',t)"><i></i></button></td><td><button class="mini" :disabled="!t.enabled" @click="$emit('runTool',t)">试运行</button></td></tr></tbody></table></div></div>
    <div v-else-if="page==='reviews'"><div class="admin-title"><div><h2>人工导诊申请</h2><p>此处记录和处理人工复核申请；尚未连接医院人员排班或通知系统。</p></div></div><div class="table-card"><table><thead><tr><th>提交时间</th><th>患者</th><th>会话</th><th>申请原因</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="review in reviews" :key="review.id"><td>{{ new Date(review.createdAt).toLocaleString() }}</td><td>{{ review.patient }}</td><td>{{ review.sessionId.slice(0,8) }}</td><td>{{ review.reason }}</td><td>{{ review.status }}</td><td><button v-if="review.status==='PENDING'" class="mini" @click="$emit('handleReview',review.id,'ACCEPTED')">接单</button><button v-if="review.status==='PENDING'" class="mini" @click="$emit('handleReview',review.id,'CLOSED')">关闭</button></td></tr><tr v-if="!reviews.length"><td colspan="6" class="empty">暂无人工导诊申请</td></tr></tbody></table></div></div>
    <div v-else><div class="admin-title"><div><h2>AI 调用观测</h2><p>展示持久化调用记录和真实执行耗时；供应商未返回 Token 时显示 0，不使用虚构指标。</p></div></div><div v-if="runtime" class="runtime-status" :class="{ready:runtime.configured,offline:!runtime.configured}"><b>{{ runtime.configured ? '模型配置已加载' : '模型未配置' }}</b><span>{{ runtime.modelName || '—' }}</span><small>{{ runtime.detail }}</small></div><div class="metric-grid"><article><b>{{ calls.length }}</b><span>Agent 调用记录</span></article><article><b class="green">{{ calls.filter(c=>c.success).length }}</b><span>成功调用</span></article><article><b>{{ calls.length?Math.round(calls.filter(c=>c.success).length/calls.length*100):0 }}%</b><span>实际成功率</span></article><article><b>{{ calls.length?Math.round(calls.reduce((n,c)=>n+c.elapsedMs,0)/calls.length):0 }}ms</b><span>实际平均耗时</span></article></div><div class="table-card"><table><thead><tr><th>调用时间</th><th>调用用途</th><th>模型/状态</th><th>Token（入/出）</th><th>耗时</th><th>结果</th></tr></thead><tbody><tr v-for="c in calls" :key="c.id"><td>{{ new Date(c.time).toLocaleString() }}</td><td><label class="tag">{{ c.purpose }}</label></td><td>{{ c.model }}</td><td>{{ c.inputTokens }} / {{ c.outputTokens }}</td><td>{{ c.elapsedMs }}ms</td><td><label class="ready">{{ c.success?'成功':'失败' }}</label></td></tr><tr v-if="!calls.length"><td colspan="6" class="empty">完成一次患者端分诊后，此处会显示 Agent 调用日志</td></tr></tbody></table></div></div>
    <div v-if="page==='knowledge' && knowledge.some(d=>d.status==='PENDING_REVIEW')" class="table-card knowledge-review"><h3>待审核资料</h3><p>请先核对医学内容和来源；批准后才会进入患者检索。</p><div v-for="d in knowledge.filter(d=>d.status==='PENDING_REVIEW')" :key="d.id"><span>{{ d.title }}</span><button class="mini" @click="$emit('approveKnowledge',d.id)">审核通过并索引</button></div></div>
  </div></section>
</template>
