<script setup lang="ts">
defineProps<{ page: string; knowledge: any[]; tools: any[]; calls: any[]; runtime: any; adminRoute: (page: string) => string; patientRoute: (page: string) => string }>()
defineEmits<{ addKnowledge: []; toggleTool: [tool: any] }>()
</script>

<template>
  <section class="admin-shell"><aside class="admin-side"><b>⌁ AI 智慧医院管理平台</b><a :class="{on:page==='dashboard'}" :href="adminRoute('dashboard')">⌂ 系统首页</a><p>AI 能力配置</p><a :class="{on:page==='knowledge'}" :href="adminRoute('knowledge')">▤ 医学知识库（RAG）</a><a :class="{on:page==='tools'}" :href="adminRoute('tools')">⚙ Agent 工具中心</a><a :class="{on:page==='observe'}" :href="adminRoute('observe')">◉ AI 调用观测</a><a :href="patientRoute('home')">← 返回患者端</a></aside><div class="admin-content">
    <div v-if="page==='dashboard'"><div class="admin-hero"><span>AI 智慧医院 · 智能导诊就诊平台</span><h1>您好，系统管理员 <label>管理员</label></h1><p>平台内置多轮预问诊与智能分诊 Agent，覆盖“预问诊 · 分诊 · 挂号”的可观测闭环。</p><b>AI 智能预问诊　 智能分诊 Agent　 RAG 医学知识库　 Agent 工具中心</b></div><h2>功能导航</h2><div class="admin-cards"><article><i>☷</i><h3>预问诊与智能导诊</h3><p>患者端多轮对话采集症情，Agent 根据症状和知识库推荐科室。</p></article><article><i>▤</i><h3>医学知识库 RAG</h3><p>资料上传、分段和向量检索，为导诊问答提供可引用依据。</p></article><article><i>⚙</i><h3>Agent 工具中心</h3><p>医院业务工具通过 MCP 边界注册、启停并记录完整调用链。</p></article><article><i>◉</i><h3>Agent 运行观测</h3><p>分诊 Agent 执行步骤、Token、耗时与成功率可追溯。</p></article></div></div>
    <div v-else-if="page==='knowledge'"><div class="admin-title"><div><h2>医学知识库 RAG</h2><p>资料上传、切片、向量化与语义检索；所有分诊建议必须返回来源依据。</p></div><button class="primary" @click="$emit('addKnowledge')">＋ 新增知识资料</button></div><div class="searchbar"><input placeholder="输入症状或问题，例如：咳嗽胸闷挂什么科"><button class="primary">检索</button></div><div class="table-card"><table><thead><tr><th>资料标题</th><th>知识片段</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody><tr v-for="d in knowledge" :key="d.id"><td><b>{{ d.title }}</b></td><td>{{ d.chunks }} 个切片</td><td><label class="ready">{{ d.status }}</label></td><td>{{ new Date(d.updatedAt).toLocaleString() }}</td><td class="blue">重新向量化</td></tr></tbody></table></div></div>
    <div v-else-if="page==='tools'"><div class="admin-title"><div><h2>Agent 工具中心</h2><p>模型仅可调用已启用的 MCP 工具；调用参数、结果与耗时会进入审计日志。</p></div></div><div class="tool-pool"><b>工具池预览（模型当前可调用）：</b><span v-for="t in tools.filter(t=>t.enabled)" :key="t.code">{{ t.code }}</span></div><div class="table-card"><table><thead><tr><th>工具编码</th><th>工具名称</th><th>工具说明（发送模型）</th><th>启用状态</th><th>操作</th></tr></thead><tbody><tr v-for="t in tools" :key="t.code"><td class="blue">{{ t.code }}</td><td><b>{{ t.name }}</b></td><td>{{ t.description }}</td><td><button class="switch" :class="{on:t.enabled}" @click="$emit('toggleTool',t)"><i></i></button></td><td><button class="mini">执行</button></td></tr></tbody></table></div></div>
    <div v-else><div class="admin-title"><div><h2>AI 调用观测</h2><p>每次模型调用的用途、Token、耗时和 Agent 工具链均会留痕，便于复盘。</p></div></div><div v-if="runtime" class="runtime-status" :class="{ready:runtime.configured,offline:!runtime.configured}"><b>{{ runtime.configured ? '模型配置已加载' : '模型未配置' }}</b><span>{{ runtime.modelName || '—' }}</span><small>{{ runtime.detail }}</small></div><div class="metric-grid"><article><b>{{ calls.length }}</b><span>模型调用总次数</span></article><article><b class="green">{{ calls.length }}</b><span>成功调用</span></article><article><b>97.8%</b><span>调用成功率</span></article><article><b>3.7s</b><span>平均单次耗时</span></article></div><div class="table-card"><table><thead><tr><th>调用时间</th><th>调用用途</th><th>模型</th><th>Token（入/出）</th><th>耗时</th><th>结果</th></tr></thead><tbody><tr v-for="c in calls" :key="c.id"><td>{{ new Date(c.time).toLocaleString() }}</td><td><label class="tag">{{ c.purpose }}</label></td><td>{{ c.model }}</td><td>{{ c.inputTokens }} / {{ c.outputTokens }}</td><td>{{ c.elapsedMs }}ms</td><td><label class="ready">成功</label></td></tr><tr v-if="!calls.length"><td colspan="6" class="empty">完成一次患者端分诊后，此处会显示 Agent 调用日志</td></tr></tbody></table></div></div>
  </div></section>
</template>
